//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class arendaEntities : DbContext
    {
        public arendaEntities()
            : base("name=arendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Авто> Авто { get; set; }
        public virtual DbSet<ВыданныеАвто> ВыданныеАвто { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Персонал> Персонал { get; set; }
        public virtual DbSet<Пол> Пол { get; set; }
        public virtual DbSet<Скидки> Скидки { get; set; }
        public virtual DbSet<Страховка> Страховка { get; set; }
        public virtual DbSet<Штрафы> Штрафы { get; set; }
    }
}
