//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Авто
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Авто()
        {
            this.ВыданныеАвто = new HashSet<ВыданныеАвто>();
        }
    
        public int ID { get; set; }
        public string Госномер { get; set; }
        public string Марка { get; set; }
        public string Модель { get; set; }
        public Nullable<int> Страховка { get; set; }
        public Nullable<int> Год_выпуска { get; set; }
        public Nullable<decimal> Стоимость_за_сутки { get; set; }
        public Nullable<int> Обслущивающий_персонал { get; set; }
        public string Категория { get; set; }
    
        public virtual Персонал Персонал { get; set; }
        public virtual Страховка Страховка1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ВыданныеАвто> ВыданныеАвто { get; set; }
    }
}
