//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Страховка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Страховка()
        {
            this.Авто = new HashSet<Авто>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Дата_начала { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Авто> Авто { get; set; }
    }
}
