//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Штрафы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Штрафы()
        {
            this.ВыданныеАвто = new HashSet<ВыданныеАвто>();
        }
    
        public int ID { get; set; }
        public string Штраф { get; set; }
        public Nullable<decimal> Сумма { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ВыданныеАвто> ВыданныеАвто { get; set; }
    }
}
